name: Publish release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to release from
        type: string
        required: true
      version:
        description: The version number to release
        type: string
        required: true
      prev_version:
        description: The previously most up-to-date version number
        type: string
        required: true

permissions:
  contents: read

jobs:
  check:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}

      - name: Check no 'TODO RELEASE' comments remain
        run: |
          if [ -z "$( grep -r --exclude-dir='.*' 'TODO RELEASE' )" ]; then
            exit 0
          else
            exit 1
          fi

      - name: Check version number matches
        run: |
          if [ -z "$( grep 'version = \"${{ inputs.version }}\"' rtree-capi/Cargo.toml )" ]; then
            exit 1
          else
            exit 0
          fi

  linux_wheel:
    name: Create Linux wheels
    needs: check
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-24.04
            target: x86_64
          - runner: ubuntu-24.04
            target: aarch64
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter --manifest-path rtree-capi/Cargo.toml
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist

  macos_wheel:
    name: Create macOS wheels
    needs: check
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-15-intel
            target: x86_64
          - runner: macos-latest
            target: aarch64
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter --manifest-path rtree-capi/Cargo.toml
      - uses: actions/upload-artifact@v6
        with:
          name: wheels-macos-${{ matrix.platform.target }}
          path: dist

  sdist:
    name: Create sdist
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist --manifest-path rtree-capi/Cargo.toml
      - uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: dist/

  pypi:
    name: Publish to PyPI
    needs: [linux_wheel, macos_wheel, sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          verbose: true
          password: ${{ secrets.PYPI_API_TOKEN }}

  github_release:
    name: Create GitHub release
    needs: pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist/

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create \
               --title ${{ inputs.version }} \
               --target ${{ inputs.branch }} \
               --generate-notes ${{ inputs.version }} \
               --notes-start-tag ${{ inputs.prev_version }} \
               dist/*
